communication_method = "amqp"
cache_capacity = 1024
async_task_limit = 32

[amqp]
exchange_url = "amqp://user:CHANGEME@localhost:5672/%2f"
tag = "data_router"
ingest_queue = "cdl.data.input"

[amqp.consume_options]
no_local = false
no_ack = false
exclusive = false
nowait = false

[monitoring]
metrics_port = 0
status_port = 0
otel_service_name = "data_router"

[services]
schema_registry_url = "http://localhost:50401"

[log]
rust_log = "info,data_router=debug"
