communication_method = "grpc"
cache_capacity = 1024
async_task_limit = 32

[grpc]
address = "0.0.0.0:50102"

[monitoring]
metrics_port = 0
status_port = 0
otel_service_name = "data_router"

[services]
schema_registry_url = "http://localhost:50401"

[log]
rust_log = "info,data_router=debug"
