cache_capacity = 1024
input_port = 50103

[services]
schema_registry_url = "http://localhost:50401"

[monitoring]
metrics_port = 0
status_port = 0
otel_service_name = "query_router"

[log]
rust_log = "info,query_router=debug"
