[package]
name = "utils"
authors = ["CDL Team"]
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

[lib]
name = "utils"
path = "src/lib.rs"

[dependencies]
# Workspace
cdl_dto     = { path    = "../dto" }
rpc         = { path    = "../rpc" }
misc_utils  = { path    = "crates/misc" }
task_utils  = { path    = "crates/task" }
communication_utils     = { path    = "crates/communication", features = ["kafka", "amqp", "grpc"] }
tracing_utils           = { path    = "crates/tracing", features = ["kafka", "grpc", "http"] } # TODO: Use these feature flags
settings_utils          = { path    = "crates/settings" }

# Crates.io
anyhow      = "1.0.43"
async-trait = "0.1.51"
config      = "0.11.0"
derive_more = { version = "0.99.16", features = ["display"] }
dirs        = "3.0.2"
hyper       = "0.14.11"
lapin       = "1.7.1"
lazy_static = "1.4.0"
rdkafka     = { version = "0.26.0", features = ["cmake-build"] }
reqwest     = { version = "0.11.4", features = ["json"] }
serde       = { version = "1.0.127", features = ["derive"] }
serde_json  = { version = "1.0.66", features = ["raw_value"] }
thiserror   = "1.0.26"
tokio       = { version = "1.10.0", features = ["rt-multi-thread"] }
tokio-amqp  = "1.0.0"
tracing     = "0.1.26"
url         = { version = "2.2.2", features = ["serde"] }
uuid        = { version = "0.8.2", features = ["v4", "serde"] }
async-graphql           = { version = "2.9.10", features = ["uuid", "opentelemetry", "tracing-futures", "tracinglib"] }
async-stream            = "0.3.2"
futures-util            = "0.3.16"
tonic                   = "0.5.2"
tracing-futures         = "0.2.5"

[dev-dependencies]
test-case = "1.2.0"
tokio       = { version = "1.10.0", features = ["rt-multi-thread", "macros", "sync"] }
