[package]
name = "api"
authors = ["CDL Team"]
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

[[bin]]
name = "api"
path = "src/main.rs"

[lib]
name = "api"
path = "src/lib.rs"

[dependencies]
# Workspace
cdl_dto     = { path = "../dto" }
misc_utils  = { path = "../utils/misc" }
rpc         = { path = "../rpc" }
settings_utils          = { path = "../utils/settings" }
communication_utils     = { path = "../utils/communication" }
tracing_utils           = { path = "../utils/tracing", features = ["with_http", "with_graphql"] }

# Crates.io
anyhow      = "1.0.43"
async-trait = "0.1.51"
bb8         = "0.7.1"
itertools   = "0.10.1"
serde       = { version = "1.0.127", features = ["derive"] }
serde_json  = "1.0.66"
thiserror   = "1.0.26"
tokio       = { version = "1.10.0", default-features = false, features = ["sync", "rt-multi-thread", "macros"] }
futures     = "0.3.16"
tracing     = "0.1.26"
uuid        = { version = "0.8.2", features = ["v4", "serde"] }
warp        = "0.3.1"
reqwest     = { version = "0.11.4", features = ["json"] }
async-stream            = "0.3.2"
async-graphql           = { version = "2.9.10", features = ["uuid", "opentelemetry", "tracing"] }
async-graphql-warp      = "2.9.10"
tracing-futures         = "0.2.5"
