[package]
name = "edge-registry"
version = "0.1.0"
authors = ["CDL Team"]
edition = "2018"
license = "Apache-2.0"

[[bin]]
name = "edge-registry"
path = "src/main.rs"

[lib]
name = "edge_registry"
path = "src/lib.rs"

[dependencies]
# Workspace
misc_utils  = { path = "../utils/crates/misc" }
rpc         = { path = "../rpc" }
utils       = { path = "../utils" }
settings_utils          = { path = "../utils/crates/settings" }
metrics_utils           = { path = "../utils/crates/metrics" }
communication_utils     = { path = "../utils/crates/communication" }
tracing_utils           = { path = "../utils/crates/tracing" }

# Crates.io
anyhow      = "1.0.42"
async-trait = "0.1.50"
futures     = "0.3.15"
itertools   = "0.10.1"
serde       = { version = "1.0.126", features = ["derive"] }
serde_json  = "1.0.64"
thiserror   = "1.0.26"
tokio       = { version = "1.8.1", features = ["rt-multi-thread", "macros", "sync"] }
tonic       = "0.5.0"
tracing     = "0.1.26"
uuid        = "0.8.2"
bb8-postgres             = { version = "0.7.0", features = ["with-uuid-0_8"] }
