[package]
name = "db-shrinker-postgres"
authors = ["CDL Team"]
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

[[bin]]
name = "db-shrinker-postgres"
path = "src/main.rs"

[dependencies]
# Workspace
utils       = { path = "../utils" }
tracing_utils           = { path = "../utils/crates/tracing" }

# Crates.io
anyhow      = "1.0.43"
clap        = "3.0.0-beta.4"
postgres    = { version = "0.19.1", features = ["with-uuid-0_8", "with-serde_json-1"] }
uuid        = { version = "0.8.2", features = ["v4", "serde"] }
serde_json  = "1.0.66"
tracing     = "0.1.26"

[dev-dependencies]
test-case = "1.2.0"
