communication_method = "kafka"
input_port = 50106
insert_destination = "cdl.data.input"

[kafka]
brokers = "localhost:9092"
group_id = "api"

[services]
schema_registry_url = "http://localhost:50401"
edge_registry_url = "http://localhost:50402"
on_demand_materializer_url = "http://localhost:50302"
query_router_url = "http://localhost:50103"

[notification_consumer]
source = "cdl.reports"

[log]
rust_log = "info,api=debug"
