input_port = 50301
cache_capacity = 1024

[postgres]
host = "localhost"
port = 5432
username = "postgres"
password = "1234"
dbname = "postgres"
schema = "public"

[kafka]
brokers = "localhost:9092"

[notifications]
enabled = true
destination = "cdl.reports"

[monitoring]
metrics_port = 0
status_port = 0
otel_service_name = "materializer_general"

[log]
rust_log = "info,materializer_general=debug"

[services]
schema_registry_url = "http://localhost:50401"
