global:
  imageRepositoryPath: epiphanyplatform/
  imageVersion: master
  imagePullPolicy: Always
  communicationMethod: "kafka"
  kafkaBrokers: 10.1.5.4:9092
  amqpConnectionString: "amqp://rabbitmq:rabbitmq@10.1.1.4:5672/%2f"
  cdlImagePullSecrets: services
  reportDestination: cdl.errors
  objectBuilderInput: cdl.materialize

api:
  port: 30152

dataRouter:
  inputSource: cdl.data.input

queryRouter:
  port: 30153

schemaRegistry:
  port: 30150
  postgresUsername: postgres
  postgresPassword: postgres
  postgresHost: 10.1.1.5
  postgresPort: 5432
  postgresDbname: cdldb

edgeRegistry:
  postgresUsername: postgres
  postgresPassword: postgres
  postgresHost: 10.1.1.5
  postgresPort: 5432
  postgresDbname: cdldb
  postgresSchema: public
  rpcPort: 50110
  consumerTag: edge-registry
  consumerSource: cdl.edge.input

webAdmin:
  port: 30151

partialUpdateEngine:
  sleepPhaseLength: 120

postgres-document:
  commandServiceReplicaCount: 1
  queryServiceReplicaCount: 1
  materializerGeneralReplicaCount: 1
  postgresUsername: postgres
  postgresPassword: postgres
  postgresHost: 10.1.1.5
  postgresPort: 5432
  postgresDbname: cdldb
  postgresSchema: public
  inputSource: cdl.document.data

druid-timeseries:
  commandServiceReplicaCount: 0
  queryServiceReplicaCount: 0
  inputSource: cdl.timeseries.data
  outputTopic: cdl.timeseries.generic-druid
  queryURL:
  tableName: CDL

victoria-metrics-timeseries:
  commandServiceReplicaCount: 0
  queryServiceReplicaCount: 0
  inputSource: cdl.timeseries2.data
  outputURL: http://infrastructure-victoria-metrics-single-server:8428/

postgres-materializer-general:
  postgresUsername: postgres
  postgresPassword: postgres
  postgresHost: 10.1.1.5
  postgresPort: 5432
  postgresDbname: cdldb
  postgresSchema: public
