input_port = 50107
chunk_capacity = 100

[notifications]
enabled = true

[kafka]
group_id = "object_builder"
ingest_topic = "cdl.materialize"

[monitoring]
otel_service_name = "object-builder"

[log]
rust_log = "info,object_builder=debug"
