[package]
name = "notification_utils"
authors = ["CDL Team"]
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
communication_utils      = { path = "../communication" }
cdl_dto     = { path = "../../../dto" }

anyhow      = "1.0.42"
tracing     = "0.1.26"
serde       = { version = "1.0.126", features = ["derive"] }
async-trait = "0.1.50"
serde_json  = "1.0.64"
